use_frameworks!

target 'AnimatedImageKit_Example' do
  pod 'AnimatedImageKit', :path => '../'

  target 'AnimatedImageKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
